// ...existing code...
init() {
    // ...existing code...
    if (!this.container) {
        console.error('LabEnvironment: container element not found!');
        return;
    }
    // ...existing code...
    this.camera = new THREE.PerspectiveCamera(75, this.container.clientWidth / this.container.clientHeight, 0.1, 1000);
    // ...existing code...
    this.renderer.setSize(this.container.clientWidth, this.container.clientHeight);
    // ...existing code...
}
// ...existing code...
// Before accessing el.clientWidth, add a null check
const el = document.getElementById('someElementId');
if (el) {
  const width = el.clientWidth;
  // ...existing code...
}
// ...existing code...